### ISSUE TITLE
Update failed for AnAction

### ISSUE THREAD

**Issue by dubrousky** [dubrousky/Mathematica-REPL#35]
Idea version:8.0.3
Plugin version:0.0.2
update failed for AnAction with ID=MathREPL.repl.simple.mathematica.Actions.MathREPLStartKernelAction: com/intellij/openapi/actionSystem/DataKeys
null

**Comment by balping** [comment]
Any idea how to resolve this?

**Comment by balping** [comment]
Related bug: https://intellij-support.jetbrains.com/hc/en-us/community/posts/206769215-NoClassDefFoundError-in-plugin

`LangDataKeys` should be used instead.
