### ISSUE TITLE
Incorrect string recognition after Put

### ISSUE THREAD

**Issue by theavey** [dubrousky/Mathematica-REPL#36]
The line `FullDefinition[output] >> "mathematicaHILLS.m"` gets the feedback "Could not parse right hand side of Put or PutAppend expression" as well as essentially missing the first quote symbol. It interprets it as opening a string at the end of the line that is then never closed.

The code runs just fine in Mathematica.
I do not know if this is an issue with the plugin or something from Mathematica, though I suspect more the latter, with no evidence.

![screen shot 2015-07-06 at 5 14 35 pm](https://cloud.githubusercontent.com/assets/8083606/8533365/8f113446-2402-11e5-993b-240f0e508b75.png)

**Comment by dubrousky** [comment]
I'll check the issue, I guess that the issue is in the quotes escaping. Could you please describe the sequense of actions in plugin that lead to the bug?

**Comment by thompcinnamon** [comment]
I’m realizing now I think this is in the Mathematica plugin not in the REPL part. I’ll post this again in the right place. Thanks.
